### ISSUE TITLE
Disable bounces for the scroll in PagingView

### ISSUE THREAD

**Issue by cedanmisquith** [ericlewis/PagingView#1]
Hi, 
I am pretty new to SwiftUI and I am trying to recreate a Peeking paging view for an existing project. I was able to achieve the peeking effect and the paging effect with your solution, however there does not seem to be a way to disable the bounces. 
Any way this can be implemented here ?

**Comment by ericlewis** [comment]
@cedanmisquith I implore you read the readme and don't use this in projects!

**Comment by cedanmisquith** [comment]
@ericlewis I have in fact read the readme and I am well aware of everything. I am not using this in any production app. Just wanted to know if it was possible to do so or not.

**Comment by ericlewis** [comment]
@cedanmisquith constrainedDeceleration might be what you are looking for then. Another approach would be to use introspect to grab the underlying scrollview and kill the bounces there.

**Comment by cedanmisquith** [comment]
@ericlewis using introspect seems like a good idea. I will try that. Thanks.

**Comment by ericlewis** [comment]
no worries. off topic, but how on earth are you seeing my replies so quickly? @cedanmisquith

**Comment by cedanmisquith** [comment]
@ericlewis I have the GitHub app on my phone 😅 so i get notified everytime you comment.

**Comment by ericlewis** [comment]
that makes sense, I always forget direct mentions send a notice right away. @cedanmisquith lol

**Comment by cedanmisquith** [comment]
@ericlewis yup 😄
